### ISSUE TITLE
[FEATURE] Configurable container hostname

### ISSUE THREAD

**Issue by Arffeh** [UdelaRInterior/ansible-role-proxmox-create-lxc#10]
**Is your feature request related to a problem? Please describe.**
Currently the container and node hostname are the same.

**Describe the solution you'd like**
configurable proxmox_hostname variable, to facilitate creation of multiple containers, with better naming.

**Describe alternatives you've considered**
Only alternative I can think of is renaming the container after running the role, but that will break idempotency.

**Comment by santiagomr** [comment]
Hi @Arffeh, first of all thanks for sharing suggestions.

There is an error regarding what you say:
>  Currently the container and node hostname are the same.

The role currently has the variable `node` to specify the FQDN of the Proxmox VE node with which it will interact (API endpoint for the Ansible's `proxmox` module).

On the other hand, the `proxmox_hostname` variable is inferred from the container FQDN (`inventory_hostname`) that is being created as a result of executing the role.

**Both values will never match if you have the variables and inventory set correctly.**

That said, your suggestion of having a specific variable to define the container's hostname (rather than inferring it from inventory) gives the role greater versatility and is easy to implement. It will be incorporated into the role soon.

**Comment by Arffeh** [comment]
Hi,

I've done the required change, but not yet pushed.

It's just a matter of moving the initial set_fact to the defaults file.
This allows the variable to be optionally set by the user.

To elaborate, yes, the node FQDN was set, but that just means I can only
generate one container, because the role will always target the node name,
as a container.

**Comment by ulvida** [comment]
Hello @Arffeh. I don't understand well what your proposal is. As @santiagomr states, hostname and node are role's variable that you can define, eventually inferred from context. 
Please, explain better your problem and goals. If not, I suggest to close this issue.

**Comment by ulvida** [comment]
Sorry: checking the code I think I understand: `proxmox_hostname` is _always_ inferred from `inventory_hostname`that, in our case, we suppose to be the FQDN of the host to be created. 

But the role may be used in other cases (for instance an inventory with IPs) where you don't want the first element of a doted nomenclature of the inventory_hostname as the proxmox hostname.
