### ISSUE TITLE
[FEATURE] Run bash on LXC after creation ?

### ISSUE THREAD

**Issue by liberodark** [UdelaRInterior/ansible-role-proxmox-create-lxc#17]
Hi,

Have see snippets just run bash on node, not on LXC container.
But you have idea for run directly scripts on lxc after creation ?

One idea is : `pct exec 100 -- apt install htop`
But if you want run a external playbook ?
You have any other way than `pct exec`

Best Regards

**Comment by santiagomr** [comment]
Hi, thank for sharing your comments.

If I'm understanding well, what you propose is to implement the possibility of invoking and executing bash scripts inside a container already running to continue with its provisioning (for example, to configure it or install packages)

The bash scripts that are executed in the Proxmox nodes by this role, are because it is strictly necessary for the creation of LXC containers and it is not possible to do it in another way (or at least we cannot find a better way to do it).

This role exists by and for container creation. Running bash scripts post-creation is out of the role scope. To keep the role simple and focused on its function, whatever bash script you want to run on an LXC should be part of your playbook flow immediately after you have invoked this role. Eg.: You could use the [ansible.builtin.script](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/script_module.html) module, or maybe some galaxy role that provides better functionality for whatever you want to do.

In Ansible, as a general rule, whatever task you are going to execute is best done by the corresponding module that uses shell commands. Otherwise the potential of Ansible in idempotency and agnostism of the platform/OS used is wasted. The example you propose (install htop) you can solve it simply with [apt module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html) in one task:
```yaml
- name: Install htop using apt module
  apt:
    name: htop
    state: present
```

**Comment by liberodark** [comment]
Hello,

Thank you for the information I know the apt role precisely.
But question was precisely even if it is not a bash script via snippet it could be via ansible.
But the only way I see it is ansible proxmox> api to create the lxc vmid 100 for example.
Then another ansible to install apt on the lxc vmid 100 start up.
Via DNS + SSH for example.

PS : Basically what I'm trying to do is the most efficient way to create + start and then provision the lxc. 
It's a shame that pve snippets can't really help for this case. 

Best Regards
